server:
  port: 8007
spring:
  application:
    name: g-security
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 971126
    url: jdbc:mysql://47.100.237.50:3306/gsec
  devtools:
    restart:
      enabled: false
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: utf-8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
