server:
  port: 8008
spring:
  application:
    name: g-webs
  devtools:
    restart:
      enabled: false
  rabbitmq:
    host: 47.100.237.50
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka
  instance:
    prefer‐ip‐address: true
